apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: $MCE_MANAGED_CLUSTER_NAME
  annotations:
    managedcluster-import-controller.open-cluster-management.io/keeping-auto-import-secret: ""
stringData:
  autoImportRetry: "2"
  kubeconfig: |
$MCE_KUBECONFIG
type: Opaque